"""
Contains code for preprocessing user inputs and data used in algorithm
"""

import json
import psycopg2
import os
from functools import wraps


class Preprocessing:
    def __init__(self):
        self.db = DBConnection()

    def get_query_results(self, sql_query):
        output = self.validate_query(sql_query) 
        query_res = self.db.execute(sql_query)
        return query_res
    
    
    def get_query_plan(self, sql_query):
        """
        Generates a Query Execution Plan (QEP) for a given SQL query.

        Args:
            sql_query (str): The SQL query for which to generate a QEP.

        Returns:
            dict: A dictionary representation of the QEP generated by PostgreSQL.
                The dictionary is in JSON format and contains detailed information
                about the steps involved in executing the query.

        Raises:
            ValueError: If the provided SQL query is invalid.
        """
        # TODO: 
        # CALL on front end raise value error 
        print("ENTERING GET QUERY PLAN")
        is_query_valid = self.validate_query(sql_query) 
        print("QUERY VALIDATION: ", is_query_valid)
        query_plan_res = self.db.execute("EXPLAIN (FORMAT JSON) " + sql_query)
        try:
            query_plan_res = query_plan_res[0][0][0]["Plan"]
        except Exception as e:
            query_plan_res = {}
            pass
        return query_plan_res

    def validate_query(self, query):
        """
        Checks if the given query string is valid.
        Returns:
            dict: A dictionary with the following keys:
                - error (bool): Indicates if an error occurred during validation.
                - error_message (str): The error message if an error occurred,
                otherwise an empty string.
        """
        result = {"error": False, "error_message": ""}
        # checks if there's a query to execute
        if not len(query):
            result["error_message"] = "There is no query to execute."
            result["error"] = True
            return result
        # if query exists check that the query is a valid query
        if not self.db.is_query_valid(query):
            result["error_message"] = "The query cannot be executed and is invalid"
            result["error"] = True
            return result
            
        return result

class DBConnection:
    def __init__(self, db_config_path: str = 'config.json'):
        """Initializes a new instance of the 'Database' class
        
        The constructor reads the database connection details from the config.json file and establishes a connection to the PostgreSQL server

        Args:
        db_config_path (str, optional): The path to the configuration file containing
        the database connection details. If not provided,
            the default value is 'config.json'
        
        Raises:
            FileNotFoundException: If the config.json file is not found
            ValueError: If the config.json fi
        
        """
       
        dir_path = os.path.dirname(os.path.realpath(__file__))
        db_config_path = os.path.join(dir_path, "config.json")

        with open(db_config_path, "r") as file:
            config_dict = json.load(file)
        self.port = config_dict['port']
        self.database = config_dict['database']
        self.user = config_dict['user']
        self.host = config_dict['host']
        self.password = config_dict['password']
        self.conn = psycopg2.connect(host=self.host, port=self.port,database=self.database,user=self.user, password=self.password)
        self.cur = self.conn.cursor()

    def execute(self, query: str):
        """Executes a query on the database and returns the results.
        Args:
        """
        try:
            self.cur.execute(query)
            query_results = self.cur.fetchall()
            return query_results
        except Exception as e:
            pass

    def is_query_valid(self, query: str):    
        """Fetches a single row from the database to check if the query is valid.
        Args:
            query (str): Query string that was entered by the user.
        Returns:
            boolean: true if query is valid, false otherwise.
        """
        try:
            self.cur.execute(query)
            self.cur.fetchone()
        except Exception as e:
            print ("Exception: is_query_valid:", e)
            return False
        return True
